import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import authOptions from '../api/auth/[...nextauth]/options';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (session === null) {
    return redirect('/signin');
  }
  return <main>{children}</main>;
}
