import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import authOptions from '../api/auth/[...nextauth]/options';
import { redirect } from 'next/navigation';
import { SidebarInset, SidebarProvider } from '@/components/common/sidebar';
import { cookies } from 'next/headers';
import AppSidebar from '@/components/common/app-sidebar';
import Header from '@/components/common/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (session === null) {
    return redirect('/signin');
  }
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar:state')?.value === 'true';
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar />
      <SidebarInset>
        <Header />
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
